// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ApiUIClient is the client API for ApiUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiUIClient interface {
	// ListEngineSpecs returns a list of API Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (ApiUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type apiUIClient struct {
	cc grpc.ClientConnInterface
}

func NewApiUIClient(cc grpc.ClientConnInterface) ApiUIClient {
	return &apiUIClient{cc}
}

func (c *apiUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (ApiUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ApiUI_ServiceDesc.Streams[0], "/v1.ApiUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &apiUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ApiUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type apiUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *apiUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *apiUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.ApiUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiUIServer is the server API for ApiUI service.
// All implementations must embed UnimplementedApiUIServer
// for forward compatibility
type ApiUIServer interface {
	// ListEngineSpecs returns a list of API Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, ApiUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedApiUIServer()
}

// UnimplementedApiUIServer must be embedded to have forward compatible implementations.
type UnimplementedApiUIServer struct {
}

func (UnimplementedApiUIServer) ListEngineSpecs(*ListEngineSpecsRequest, ApiUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedApiUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedApiUIServer) mustEmbedUnimplementedApiUIServer() {}

// UnsafeApiUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiUIServer will
// result in compilation errors.
type UnsafeApiUIServer interface {
	mustEmbedUnimplementedApiUIServer()
}

func RegisterApiUIServer(s grpc.ServiceRegistrar, srv ApiUIServer) {
	s.RegisterService(&ApiUI_ServiceDesc, srv)
}

func _ApiUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiUIServer).ListEngineSpecs(m, &apiUIListEngineSpecsServer{stream})
}

type ApiUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type apiUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *apiUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ApiUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ApiUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApiUI_ServiceDesc is the grpc.ServiceDesc for ApiUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApiUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ApiUI",
	HandlerType: (*ApiUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _ApiUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _ApiUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api-ui.proto",
}
